Repository nanograv/PINT, pull requests merged in 2020-12, with the labels that each got.

#843 Remove unneeded test
  tests/test_erfautils.py
Labels: bug fix

#835 New clock files
  docs/explanation.rst
  src/pint/datafiles/README.md
  src/pint/datafiles/time_ao.dat
  src/pint/datafiles/time_gbt.dat
Labels: enhancement

#842 Fix astrometry time scale
  src/pint/models/astrometry.py
  src/pint/utils.py
  tests/test_Galactic.py
Labels: bug fix

#838 Invalidate pickles based on settings
  src/pint/toa.py
  tests/test_toa_pickle.py
Labels: enhancement

#834 Add check for STIGMA <= 0
  src/pint/models/binary_ell1.py
  tests/test_stigma.py
Labels: enhancement

#829 Getattr cleanup
  src/pint/models/absolute_phase.py
  src/pint/models/astrometry.py
  src/pint/models/binary_ddk.py
  src/pint/models/dispersion_model.py
  src/pint/models/frequency_dependent.py
  src/pint/models/ifunc.py
  src/pint/models/jump.py
  src/pint/models/noise_model.py
  src/pint/models/pulsar_binary.py
  src/pint/models/solar_system_shapiro.py
  src/pint/models/solar_wind_dispersion.py
  src/pint/models/stand_alone_psr_binaries/DDK_model.py
  src/pint/models/timing_model.py
  src/pint/models/troposphere_delay.py
  src/pint/models/wave.py
  tests/test_timing_model.py
Labels: bug fix

#844 Getitem implementation for TOAs
  docs/examples/time_a_pulsar.py
  docs/tutorials.rst
  src/pint/toa.py
  tests/test_toa_indexing.py
Labels: enhancement

#922 Add component build example
  docs/examples/How_to_build_a_timing_model_component.py
  docs/tutorials.rst
  src/pint/residuals.py
Labels: version 0.8
