Repository nanograv/PINT, pull requests merged in 2021-08, with the labels that each got.

#1102 Move utils.py to derived_quantities.py
  docs/examples/Simulate_and_make_MassMass.py
  src/pint/derived_quantities.py
  src/pint/fitter.py
  src/pint/utils.py
  tests/test_derived_quantities.py
  tests/test_utils.py
Labels: reviewer comments need response

#1090 Update downloads to use astropy; also add CI check for NANOGrav ephem server
  .github/workflows/ci_test.yml
  check_ephemeris_connection.py
  src/pint/solar_system_ephemerides.py
  tox.ini
Labels: awaiting review

#1114 Fix for improper arguments in fitter.get_summary()
  src/pint/fitter.py
  tests/test_fitter.py
Labels: bug fix, awaiting review

#1112 Fix allow_local for nicer and others
  src/pint/event_toas.py
Labels: bug fix

#1120 Make `change_binary_epoch` more cautious and also not broken
  src/pint/models/binary_ell1.py
  src/pint/models/pulsar_binary.py
  tests/test_change_epoch.py
Labels: bug fix, awaiting review, minor

#1125 Fix for issue #1109
  src/pint/utils.py
Labels: minor

#1129 Fix bug in d_phase_d_toa()
  src/pint/models/timing_model.py
  tests/test_d_phase_d_toa.py
Labels: awaiting review, minor

#1131 Update Pintk random models operation
  src/pint/pintk/plk.py
  src/pint/pintk/pulsar.py
  src/pint/simulation.py
Labels: awaiting review

#1110 Minor compatibility improvements
  docs/examples/How_to_build_a_timing_model_component.py
  docs/examples/understanding_fitters.py
  src/pint/models/astrometry.py
  src/pint/models/dispersion_model.py
  src/pint/models/timing_model.py
  tests/test_astrometry.py
  tests/test_change_epoch.py
  tests/test_model_manual.py
  tests/test_timing_model.py
Labels: bug fix, minor
