Repository nanograv/PINT, pull requests merged in 2021-11, with the labels that each got.

#1147 Eliminate spurious "Data points out of range in clock file" warnings
  src/pint/observatory/clock_file.py
Labels: awaiting review

#1136 Fix gridding, allow gridding based on functions.
  docs/examples/Grid_J0740.py
  docs/examples/grid_parameters.py
  docs/working-with-notebooks.rst
  src/pint/data/examples/J0740+6620.FCP+21.wb.DMX3.0.par
  src/pint/data/examples/J0740+6620.FCP+21.wb.tim
  src/pint/fitter.py
  src/pint/gridutils.py
  tests/test_grid.py
Labels: awaiting review

#1148 Transform models ECL <-> ICRS
  src/pint/models/astrometry.py
  src/pint/models/timing_model.py
  tests/test_modelconversions.py
Labels: awaiting review

#1026 Rewrite model builder
  docs/examples/build_model_from_scratch.py
  docs/examples/check_phase_connection.py
  src/pint/config.py
  src/pint/models/model_builder.py
  src/pint/models/parameter.py
  src/pint/models/pulsar_binary.py
  src/pint/models/spindown.py
  src/pint/models/timing_model.py
  tests/datafile/B1855+09_NANOGrav_dfg+12_modified.par
  tests/datafile/J0613-0200_NANOGrav_dfg+12_TAI_FB90.par
  tests/datafile/testtimes.par
  tests/test_all_component_and_model_builder.py
  tests/test_change_epoch.py
  tests/test_fake_toas.py
  tests/test_model_derivatives.py
  tests/test_model_manual.py
  tests/test_parameters.py
  tests/test_process_parfile.py
  tests/test_spindown.py
  tests/test_timing_model.py
  tests/test_utils.py
  tests/test_variety_parfiles.py
Labels: needs discussion, awaiting review, ready for new iteration review

#1154 Fixing tutorial notebooks
  docs/conf.py
  docs/examples/Grid_J0740.py
  docs/examples/grid_parameters.py
  docs/tutorials.rst
Labels: bug fix, awaiting review
