Repository nanograv/PINT, pull requests merged in 2022-04, with the labels that each got.

#1193 Fixes profiling code
  profiling/NGC6440E.par
  profiling/README.txt
  profiling/bench_chisq_grid.py
  profiling/bench_chisq_grid_WLSFitter.py
  profiling/high_level_benchmark.py
  profiling/parser.py
  requirements_dev.txt
  src/pint/pintk/pulsar.py
Labels: bug fix, awaiting review

#1189 Update gridding
  requirements_dev.txt
  src/pint/gridutils.py
  src/pint/models/binary_ddk.py
  tests/test_grid.py
  tox.ini
Labels: awaiting review

#1187 Compute alternative Kopeikin solutions
  src/pint/models/binary_ddk.py
Labels: awaiting review

#1222 Fix prefixParameter frozen inheritance
  CHANGELOG.md
  src/pint/models/parameter.py
  tests/test_prefixparaminheritance.py
Labels: bug fix
