Repository nanograv/PINT, pull requests merged in 2022-06, with the labels that each got.

#1259 Color TOAs by jump in pintk
  CHANGELOG.md
  src/pint/pintk/colormodes.py
  src/pint/pintk/plk.py
Labels: enhancement

#1274 Fixing logic for remove_DMX_range() inputs
  src/pint/models/dispersion_model.py
Labels: bug fix

#1270 Fix directories of INCLUDE files
  CHANGELOG.md
  src/pint/toa.py
  tests/test_toa_reader.py
Labels: bug fix, minor

#1281 Remove explicit updating of IERSB/leapsecond tables
  CHANGELOG.md
  src/pint/erfautils.py
  src/pint/observatory/__init__.py
  src/pint/observatory/topo_obs.py
  src/pint/toa.py
Labels: awaiting review

#1308 Updated logging docs and example
  docs/controlling-logging.rst
  docs/examples/PINT_walkthrough.py
Labels: awaiting review

#1309 Handle no clock files better
  CHANGELOG.md
  src/pint/observatory/__init__.py
  src/pint/observatory/clock_file.py
  src/pint/observatory/observatories.py
  src/pint/observatory/topo_obs.py
  tests/test_observatory.py
Labels: awaiting review

#1318 Change update frequency for index.txt
  CHANGELOG.md
  src/pint/observatory/global_clock_corrections.py
Labels: awaiting review, minor
