Repository nanograv/PINT, pull requests merged in 2022-05, with the labels that each got.

#1225 Tweak logging
  src/pint/logging.py
  src/pint/models/stand_alone_psr_binaries/DDK_model.py
Labels: awaiting review

#1236 Report the observatory when TEMPO/TEMPO2 needed.
  src/pint/observatory/topo_obs.py
Labels: bug fix, minor

#1230 Fix DMDATA output for non-pint format
  CHANGELOG.md
  src/pint/models/parameter.py
  src/pint/models/timing_model.py
  tests/test_parameters.py
  tests/test_parfile_writing_format.py
Labels: bug fix, awaiting review

#1176 Add warning when using A1DOT with DDK models
  CHANGELOG.md
  src/pint/logging.py
  src/pint/models/binary_ddk.py
  tests/test_ddk.py
Labels: awaiting review

#1244 Use EQUADs and EFACs in WLS fitters
  CHANGELOG.md
  src/pint/fitter.py
  tests/test_fitter_compare.py
Labels: bug fix, awaiting review

#1249 PINTk improvements
  src/pint/pintk/paredit.py
  src/pint/pintk/plk.py
  src/pint/pintk/pulsar.py
  src/pint/pintk/timedit.py
  src/pint/scripts/pintk.py
Labels: awaiting review
