Repository nanograv/PINT, pull requests merged in 2023-02, with the labels that each got.

#1519 Allow docs build without examples (much faster)
  .readthedocs.yml
  CHANGELOG.md
  docs/Makefile
  docs/conf.py
  requirements_dev.txt
Labels: awaiting review

#1527 Fix PLDM test error
  CHANGELOG.md
  tests/test_pldmnoise.py
Labels: awaiting review

#1284 Multiprocessing functionality for event_optimize
  src/pint/scripts/event_optimize.py
  tests/test_event_optimize.py
  tox.ini
Labels: needs discussion

#1511 Create TOAs from numpy array or Time object directly
  CHANGELOG.md
  docs/user-questions.rst
  src/pint/fermi_toas.py
  src/pint/models/absolute_phase.py
  src/pint/polycos.py
  src/pint/scripts/fermiphase.py
  src/pint/scripts/pintbary.py
  src/pint/simulation.py
  src/pint/toa.py
  tests/test_fake_toas.py
  tests/test_infostrings.py
  tests/test_polycos.py
  tests/test_toa.py
  tests/test_toa_create.py
  tests/test_toa_writer.py
Labels: awaiting review

#1496 Function parameters
  CHANGELOG.md
  src/pint/models/binary_dd.py
  src/pint/models/binary_ddk.py
  src/pint/models/binary_ell1.py
  src/pint/models/parameter.py
  src/pint/models/pulsar_binary.py
  src/pint/models/stand_alone_psr_binaries/binary_generic.py
  src/pint/models/timing_model.py
  tests/test_compare.py
  tests/test_funcpar.py
  tests/utils.py
Labels: enhancement, awaiting review

#1537 Fix clock selection for random models
  CHANGELOG.md
  src/pint/models/stand_alone_psr_binaries/binary_generic.py
  src/pint/simulation.py
  tests/test_random_models.py
Labels: bug fix, awaiting review
