Repository nanograv/PINT, pull requests merged in 2024-02, with the labels that each got.

#1724 Added spacecraft as alias for geocenter
  CHANGELOG-unreleased.md
  src/pint/observatory/special_locations.py
  tests/test_toa_create.py
Labels: bug fix, awaiting review, minor

#1717 Allow simulated TOAs to maintain a non-zero mean
  CHANGELOG-unreleased.md
  src/pint/simulation.py
  tests/test_fake_toas.py
Labels: awaiting review

#1720 Improve clock error reporting
  .pre-commit-config.yaml
  CHANGELOG-unreleased.md
  src/pint/observatory/clock_file.py
  tests/test_clock_file.py
Labels: enhancement, awaiting review, minor
