Repository nanograv/PINT, pull requests merged in 2024-05, with the labels that each got.

#1748 Make `Astrometry` & `SolarSystemShapiro` faster
  CHANGELOG-unreleased.md
  src/pint/models/astrometry.py
  src/pint/models/solar_system_shapiro.py
  src/pint/simulation.py
  tests/test_wavex.py
Labels: awaiting review

#1750 Allow pintk to read par files with `UNITS TCB` and `BINARY T2` + Exclude function parameters in pintk
  CHANGELOG-unreleased.md
  src/pint/pintk/plk.py
  src/pint/pintk/pulsar.py
Labels: awaiting review

#1761 Fix #1759 (coordinate comparison identity)
  CHANGELOG-unreleased.md
  tests/test_Galactic.py
Labels: awaiting review

#1758 Updated location of CCERA
  CHANGELOG-unreleased.md
  src/pint/data/runtime/observatories.json
Labels: awaiting review, minor

#1756 Custom type definitions
  src/pint/__init__.py
  src/pint/models/astrometry.py
  src/pint/simulation.py
Labels: enhancement, awaiting review

#1767 Try citation.cff
  citation.cff
Labels: awaiting review, minor

#1732 Fixed bug in residual calculation when adding or removing phase wraps…
  src/pint/pintk/pulsar.py
Labels: bug fix, pintk

#1755 Type hints in `pint.toa` and `get_model` & `get_model_and_toas` functions
  CHANGELOG-unreleased.md
  src/pint/models/model_builder.py
  src/pint/toa.py
  src/pint/types.py
  tests/test_pmtransform_units.py
Labels: awaiting review
