Repository nanograv/PINT, pull requests merged in 2024-08, with the labels that each got.

#1815 Fixed BIC
  CHANGELOG-unreleased.md
  src/pint/utils.py
Labels: bug fix

#1817 Type hints in `residuals.py` & bump `black` to 24.x
  CHANGELOG-unreleased.md
  src/pint/binaryconvert.py
  src/pint/derived_quantities.py
  src/pint/eventstats.py
  src/pint/fermi_toas.py
  src/pint/gridutils.py
  src/pint/models/priors.py
  src/pint/models/stand_alone_psr_binaries/DDGR_model.py
  src/pint/models/stand_alone_psr_binaries/DDH_model.py
  src/pint/models/stand_alone_psr_binaries/DDK_model.py
  src/pint/models/stand_alone_psr_binaries/DDS_model.py
  src/pint/models/stand_alone_psr_binaries/DD_model.py
  src/pint/models/stand_alone_psr_binaries/ELL1_model.py
  src/pint/models/stand_alone_psr_binaries/ELL1k_model.py
  src/pint/models/troposphere_delay.py
  src/pint/observatory/global_clock_corrections.py
  src/pint/orbital/kepler.py
  src/pint/output/publish.py
  src/pint/pint_matrix.py
  src/pint/pintk/colormodes.py
  src/pint/residuals.py
  src/pint/scripts/pintpublish.py
  src/pint/templates/lcfitters.py
  src/pint/templates/lcnorm.py
  src/pint/toa_select.py
  tests/datafile/get_tempo2_result.py
  tests/test_B1855.py
  tests/test_B1855_9yrs.py
  tests/test_B1953.py
  tests/test_J0613.py
  tests/test_TDB_method.py
  tests/test_dd.py
  tests/test_design_matrix.py
  tests/test_dmefac_dmequad.py
  tests/test_early_chime_data.py
  tests/test_fbx.py
  tests/test_fd.py
  tests/test_infostrings.py
  tests/test_parfile_writing.py
  tests/test_pldmnoise.py
  tests/test_plot_utils.py
  tests/test_pulsar_position.py
  tests/test_toa_flag.py
  tests/test_variety_parfiles.py
  tests/utils.py
  tox.ini
Labels: awaiting review, minor

#1821 Change default of FDJUMPLOG to Y
  CHANGELOG-unreleased.md
  src/pint/models/fdjump.py
  tests/test_fdjump.py
Labels: awaiting review

#1813 More typehints
  CHANGELOG-unreleased.md
  src/pint/binaryconvert.py
  src/pint/config.py
  src/pint/erfautils.py
  src/pint/fits_utils.py
  src/pint/gridutils.py
  src/pint/logging.py
  src/pint/modelutils.py
Labels: awaiting review

#1819 Include frozen in `maskParameter.__repr__`
  CHANGELOG-unreleased.md
  src/pint/models/parameter.py
Labels: awaiting review, minor

#1827 Made SWXP frozen by default, even for first segment
  CHANGELOG-unreleased.md
  src/pint/models/solar_wind_dispersion.py
  tests/test_solar_wind.py
Labels: bug fix, minor

#1828 Paper 2 info in `README` file and `citation.cff`
  CHANGELOG-unreleased.md
  README.rst
  citation.cff
Labels: awaiting review, minor

#1833 Fix documentation of local ephemerides
  CHANGELOG-unreleased.md
  docs/explanation.rst
Labels: awaiting review, minor
