Repository nanograv/PINT, pull requests merged in 2024-06, with the labels that each got.

#1775 Whitened residuals in `pintk`
  CHANGELOG-unreleased.md
  src/pint/pintk/plk.py
  src/pint/pintk/pulsar.py
Labels: awaiting review

#1616 Chromatic delay similar to dispersion delay
  CHANGELOG-unreleased.md
  src/pint/models/__init__.py
  src/pint/models/chromatic_model.py
  src/pint/models/dispersion_model.py
  src/pint/models/tcb_conversion.py
  tests/test_chromatic.py
Labels: awaiting review

#1778 Remove debugging statement
  src/pint/utils.py
Labels: minor

#1784 Minimal fixes for numpy 2.0
  CHANGELOG-unreleased.md
  src/pint/fitter.py
  src/pint/models/model_builder.py
  src/pint/models/parameter.py
  src/pint/plot_utils.py
  src/pint/pulsar_mjd.py
  src/pint/scripts/event_optimize.py
  src/pint/toa.py
  tests/test_model_derivatives.py
  tests/test_precision.py
Labels: bug fix, awaiting review

#1782 Fixed docstring in one simulation routine
  src/pint/simulation.py
Labels: minor

#1781 `TOAs.get_Tspan()` method
  CHANGELOG-unreleased.md
  src/pint/toa.py
  tests/test_toa.py
Labels: awaiting review, minor

#1794 Fix removal of top-level parameter
  CHANGELOG-unreleased.md
  src/pint/models/timing_model.py
  tests/test_parameters.py
Labels: bug fix, awaiting review, minor

#1790 Handle BIPM and wideband DMs correctly in `make_fake_toas_fromtim`
  CHANGELOG-unreleased.md
  src/pint/simulation.py
  tests/test_fake_toas.py
Labels: bug fix, awaiting review, minor
