Repository nanograv/PINT, pull requests merged in 2024-04, with the labels that each got.

#1728 Removed np.compat.long (deprecated)
  CHANGELOG-unreleased.md
  src/pint/models/stand_alone_psr_binaries/binary_orbits.py
Labels: awaiting review, minor

#1730 Fix #1729
  CHANGELOG-unreleased.md
  src/pint/models/timing_model.py
Labels: bug fix, awaiting review, minor

#1735 Changed error bars to scaled for pintk
  CHANGELOG-unreleased.md
  src/pint/pintk/plk.py
Labels: enhancement, awaiting review

#1738 Fixed common CI failure in `tests/test_observatory.py::test_json_observatory_input_latlon`
  CHANGELOG-unreleased.md
  tests/test_observatory.py
Labels: bug fix, awaiting review

#1731 FDJUMPDM : System-dependent DM offset
  CHANGELOG-unreleased.md
  docs/explanation.rst
  src/pint/models/__init__.py
  src/pint/models/dispersion_model.py
  tests/test_fdjump.py
Labels: awaiting review

#1737 Proper motion conversion/calculations can now uniformly use float, Quantity, or Time
  CHANGELOG.md
  src/pint/models/astrometry.py
  src/pint/models/timing_model.py
  tests/test_pmtransform_units.py
Labels: awaiting review

#1695 Guess binary model & add conversion script
  CHANGELOG-unreleased.md
  setup.cfg
  src/pint/models/model_builder.py
  src/pint/models/timing_model.py
  src/pint/scripts/t2binary2pint.py
  tests/test_process_parfile.py
  tests/test_t2binary2pint.py
Labels: enhancement, awaiting review

#1741 Bayesian information criterion
  CHANGELOG-unreleased.md
  src/pint/utils.py
  tests/test_utils.py
Labels: awaiting review

#1747 Allow "CLK UNCORR" in par files
  CHANGELOG-unreleased.md
  docs/explanation.rst
  src/pint/toa.py
  tests/datafile/J0030+0451.mdc1.par
  tests/datafile/J0030+0451.mdc1.tim
  tests/test_all_component_and_model_builder.py
  tests/test_clockcorr.py
Labels: awaiting review
