Repository nanograv/PINT, pull requests merged in 2025-03, with the labels that each got.

#1888 Fix #1853
  CHANGELOG-unreleased.md
  src/pint/polycos.py
Labels: awaiting review, minor

#1896 Fix indexing while computing `Fitter.resids.noise_ampls`
  CHANGELOG-unreleased.md
  src/pint/fitter.py
  src/pint/models/timing_model.py
  tests/test_gls_fitter.py
  tests/test_noise_models.py
  tests/test_noisefit.py
Labels: bug fix, awaiting review

#1877 More correct low-rank expansion of powerlaw noise
  CHANGELOG-unreleased.md
  src/pint/models/noise_model.py
  tests/test_noise_models.py
  tests/test_plchromnoise.py
  tests/test_pldmnoise.py
Labels: enhancement, awaiting review
